### PR TITLE
Revert "Confirmation Dialog before deleting something from the tickets/ trips or transportation mean table"

### PR DESCRIPTION
**Pull request by EslemOuederni**
I'm reverting this, since it's not successfully deleting the items, I'll push the new change and you can see in the Mean of Transport how I changed it ! Thank you for your work nonetheless

### CODE REVIEW

**Comment by vOid9201** [comment]
Mam can  you tell me wether the changes which i made was working for any other table or it was working for none of them .

**Comment by EslemOuederni** [comment]
> Mam can you tell me wether the changes which i made was working for any other table or it was working for none of them .
You did fix a couple of things, but you did miss where instead of setting toBeDeleted as a state of true or false, I changed it to track the `item_id` that will be deleted.
When you click on the delete icon it will fire this :
`<button
                onClick={(e) => {
                  console.log(item._id);
                  settobeDeleted(item._id);
                  setShowDelete(true);
                }}
              >`
-> It will both show the **modal** + **settobeDeleted** to the specific item_id, because if you don't do it, it'll delete the last row of the table.
Here's the modal : 
` {showDelete && (
                  <Modal
                    open={showDelete}
                    setOpen={setShowDelete}
                    content="Are you sure you want to delete this Transport from your list ?"
                    handle={(e) => handleDelete(tobeDeleted)}
                    button={"Delete"}
                  />
                )}`
-> I'm passing tobeDeleted in the handleDelete
**Do you want to try again with the tickets and trip table ? I have only fixed the TransportTable**

**Comment by vOid9201** [comment]
mam i have a doubt the functioning related to the handle is working can you please explain it to me . And yeah I can again give it a go to tickets and trip table.

**Comment by vOid9201** [comment]
I did not get the point you are making : (

**Comment by EslemOuederni** [comment]
I hope these images will explain what I'm trying to say, When I click here the delete icon
deleteicon
The modal shows up
deletebtn
Which is what you've done right ? but when I click on the delete button that I highlighted in the picture, nothing happens. It basically doesn't delete the item in the row. So basically the modal shows up but the delete method isn't working.

**Comment by vOid9201** [comment]
Is it still happening with the solution you come up with ??

**Comment by EslemOuederni** [comment]
No I think I've fixed it, but you try it in case there's an issue ;)

**Comment by vOid9201** [comment]
Okay I will try it thanks for so much information 
And sorry also I have wasted so much of your time 🥲🥲 , further can I still deal with the same for other table as well or you have done it

**Comment by EslemOuederni** [comment]
No it's no problem, I'm happy that someone is contributing to my project. I probably should have reviewed your code well before merging, except I'm new to open source. Thank you and good luck ! Think of this project as a space to learn ^^

**Pull request merged**
